name: Metrics

on:
  push:
    branches:
      - main
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          base: header, repositories
          config_timezone: America/New_York
          filename: metrics.classic.svg
          plugin_languages: yes
          plugin_lines: yes
          template: classic
          token: ${{ secrets.METRICS_TOKEN }}
          user: jryantz
